/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CompressionLib */

#ifndef _Included_CompressionLib
#define _Included_CompressionLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CompressionLib
 * Method:    compress
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CompressionLib_compress
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     CompressionLib
 * Method:    decompress
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CompressionLib_decompress
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
